version: "3.9"

services:
  hw2:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code

  hw2-db:
    image: postgres:10.11-alpine
