version: "3.9"

services:
  hw12backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code

networks:
  default:
    external:
      name: hw1
